// mfes/header/src/App.tsx
import { useEffect, useState } from "react";
import { EventBus } from "./EventBus";

export default function Header() {
  const [count, setCount] = useState(0);
  const [globalCount, setGlobalCount] = useState(0);

  useEffect(() => {
    EventBus.on("globalIncrement", () => {
      setGlobalCount((prev) => ++prev);
    });
  }, []);

  return (
    <div>
      Header:{" "}
      <button onClick={() => setCount((prev) => ++prev)}>Inner: {count}</button>
      <button onClick={() => EventBus.emit("globalIncrement")}>
        Global: {globalCount}
      </button>
    </div>
  );
}

// mfes/footer/src/App.vue
<template>
  <div>
    Footer:
    <button @click="handleInc">Inner: {{ count }}</button>
    <button @click="handleGlobalInc">Global: {{ globalCount }}</button>
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref } from "vue";
import { EventBus } from "./EventBus";

const count = ref(0);
const globalCount = ref(0);

const handleInc = () => {
  count.value++;
};

const handleGlobalInc = () => {
  EventBus.emit("globalIncrement");
};

const handleGlobalIncrement = () => {
  globalCount.value++;
};

onMounted(() => {
  EventBus.on("globalIncrement", handleGlobalIncrement);
});
</script>

<style>
</style>
